// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RagilHadiworoApp.Models;

#nullable disable

namespace RagilHadiworoApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RagilHadiworoApp.Models.Agunan", b =>
                {
                    b.Property<string>("AgunanID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IDCustomer")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("AgunanID");

                    b.HasIndex("IDCustomer");

                    b.ToTable("Agunans");
                });

            modelBuilder.Entity("RagilHadiworoApp.Models.Customer", b =>
                {
                    b.Property<string>("IDCustomer")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("AccountNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IDCustomer");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("RagilHadiworoApp.Models.Funding", b =>
                {
                    b.Property<string>("IDFunding")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IDCustomer")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IDFunding");

                    b.HasIndex("IDCustomer");

                    b.ToTable("Fundings");
                });

            modelBuilder.Entity("RagilHadiworoApp.Models.Lending", b =>
                {
                    b.Property<string>("IDLending")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IDCustomer")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Plafond")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IDLending");

                    b.HasIndex("IDCustomer");

                    b.ToTable("Lendings");
                });

            modelBuilder.Entity("RagilHadiworoApp.Models.Agunan", b =>
                {
                    b.HasOne("RagilHadiworoApp.Models.Customer", "Customer")
                        .WithMany("Agunans")
                        .HasForeignKey("IDCustomer")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("RagilHadiworoApp.Models.Funding", b =>
                {
                    b.HasOne("RagilHadiworoApp.Models.Customer", "Customer")
                        .WithMany("Fundings")
                        .HasForeignKey("IDCustomer")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("RagilHadiworoApp.Models.Lending", b =>
                {
                    b.HasOne("RagilHadiworoApp.Models.Customer", "Customer")
                        .WithMany("Lendings")
                        .HasForeignKey("IDCustomer")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("RagilHadiworoApp.Models.Customer", b =>
                {
                    b.Navigation("Agunans");

                    b.Navigation("Fundings");

                    b.Navigation("Lendings");
                });
#pragma warning restore 612, 618
        }
    }
}
